'use strict';

const CORE_DEFAULT_SETTINGS = {
    pageSize: 'A4',
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
    fontPreset: 'system-serif',
    fontFamily: "'Times New Roman', Times, serif",
    fontHeadingPreset: '',
    fontMarginBoxPreset: '',
    fontSize: 12,
    lineHeight: 1.5,
    decorationColor: '#000000',
    pageNumberPosition: 'footer-center',
    pageNumberStyle: 'simple',
    pageNumberStartPage: 1,
    firstPageHideHeader: false,
    firstPageHideFooter: false,
    firstPageSkipNumber: false,
    preBodyHideHeader: true,
    preBodyHideFooter: true,
    headerLeft: '',
    headerCenter: '',
    headerRight: '',
    headerRule: true,
    headerRuleColor: '#000000',
    headerFontSize: 9,
    footerLeft: '',
    footerCenter: '',
    footerRight: '',
    footerRule: true,
    footerRuleColor: '#000000',
    footerFontSize: 9,
    limitImageToPage: true,
    keepImageTogether: true,
    repeatTableHeader: true,
    avoidTableRowBreaks: true,
    pageBackground: '',
    pageBackgroundEffect: 'none',
    customCss: '',
    theme: '',
    template: '',
    dynamicChoices: {},
};

const CORE_SETTING_KEY_MAP = {
    page_size: { target: 'pageSize', type: 'string' },
    margin_top: { target: 'marginTop', type: 'number' },
    margin_bottom: { target: 'marginBottom', type: 'number' },
    margin_left: { target: 'marginLeft', type: 'number' },
    margin_right: { target: 'marginRight', type: 'number' },
    font_preset: { target: 'fontPreset', type: 'string' },
    font_family: { target: 'fontFamily', type: 'string' },
    font_heading_preset: { target: 'fontHeadingPreset', type: 'string' },
    font_margin_box_preset: { target: 'fontMarginBoxPreset', type: 'string' },
    font_size: { target: 'fontSize', type: 'number' },
    line_height: { target: 'lineHeight', type: 'number' },
    decoration_color: { target: 'decorationColor', type: 'string' },
    page_number_position: { target: 'pageNumberPosition', type: 'string' },
    page_number_style: { target: 'pageNumberStyle', type: 'string' },
    page_number_start_page: { target: 'pageNumberStartPage', type: 'number' },
    first_page_hide_header: { target: 'firstPageHideHeader', type: 'boolean' },
    first_page_hide_footer: { target: 'firstPageHideFooter', type: 'boolean' },
    first_page_skip_number: { target: 'firstPageSkipNumber', type: 'boolean' },
    pre_body_hide_header: { target: 'preBodyHideHeader', type: 'boolean' },
    pre_body_hide_footer: { target: 'preBodyHideFooter', type: 'boolean' },
    header_left: { target: 'headerLeft', type: 'string' },
    header_center: { target: 'headerCenter', type: 'string' },
    header_right: { target: 'headerRight', type: 'string' },
    header_rule: { target: 'headerRule', type: 'boolean' },
    header_rule_color: { target: 'headerRuleColor', type: 'string' },
    header_font_size: { target: 'headerFontSize', type: 'number' },
    footer_left: { target: 'footerLeft', type: 'string' },
    footer_center: { target: 'footerCenter', type: 'string' },
    footer_right: { target: 'footerRight', type: 'string' },
    footer_rule: { target: 'footerRule', type: 'boolean' },
    footer_rule_color: { target: 'footerRuleColor', type: 'string' },
    footer_font_size: { target: 'footerFontSize', type: 'number' },
    limit_image_to_page: { target: 'limitImageToPage', type: 'boolean' },
    keep_image_together: { target: 'keepImageTogether', type: 'boolean' },
    repeat_table_header: { target: 'repeatTableHeader', type: 'boolean' },
    avoid_table_row_breaks: { target: 'avoidTableRowBreaks', type: 'boolean' },
    page_background: { target: 'pageBackground', type: 'string' },
    page_background_effect: { target: 'pageBackgroundEffect', type: 'string' },
    custom_css: { target: 'customCss', type: 'string' },
    theme: { target: 'theme', type: 'string' },
    template: { target: 'template', type: 'string' },
};

module.exports = {
    CORE_DEFAULT_SETTINGS,
    CORE_SETTING_KEY_MAP,
};