/**
 * embed.js — pdf-lib round-trip: embed and extract markdown in a PDF
 *
 * This validates the .md.pdf file format:
 *   1. Take a PDF (raw PDF bytes, no embedded markdown yet)
 *   2. Attach the markdown source as a named embedded file ('source.md')
 *   3. Write the combined file as out/output.md.pdf
 *   4. Re-open the .md.pdf, extract the 'source.md' attachment, decode it
 *   5. Assert the extracted text equals the original markdown (byte-for-byte)
 *
 * Usage: node src/embed.js [input.pdf] [source.md] [output.md.pdf]
 *   Defaults use the files generated by convert.js.
 *
 * This also exports the two core helpers used by the VS Code extension:
 *   embedMarkdownInPdf(pdfBytes, markdownStr) → Uint8Array
 *   extractMarkdownFromPdf(pdfBytes)           → string | null
 */

'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const { PDFDocument } = require('pdf-lib');

/**
 * Embed a markdown string as a named file attachment inside an existing PDF.
 *
 * @param {Uint8Array|Buffer} pdfBytes   Raw bytes of the base PDF
 * @param {string}           markdown   Markdown source to embed
 * @returns {Promise<Uint8Array>}        Modified PDF bytes with the attachment
 */
async function embedMarkdownInPdf(pdfBytes, markdown) {
    const doc = await PDFDocument.load(pdfBytes);

    const encoded = Buffer.from(markdown, 'utf8');

    // Embed as a file attachment named 'source.md'
    await doc.attach(encoded, 'source.md', {
        mimeType: 'text/markdown',
        description: 'Markdown source for this document',
        creationDate: new Date(),
        modificationDate: new Date(),
    });

    return doc.save();
}

/**
 * Extract the embedded markdown string from a .md.pdf file.
 *
 * @param {Uint8Array|Buffer} pdfBytes  Raw bytes of a .md.pdf file
 * @returns {Promise<string|null>}      The markdown string, or null if not found
 */
async function extractMarkdownFromPdf(pdfBytes) {
    const { PDFName, PDFDict, PDFArray } = require('pdf-lib');
    const doc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });

    // Navigate the PDF name tree: Catalog → Names → EmbeddedFiles → Names → [name, fileSpec, ...]
    const catalog = doc.catalog;
    const namesDict = catalog.lookupMaybe(PDFName.of('Names'), PDFDict);
    if (!namesDict) return null;

    const embeddedFiles = namesDict.lookupMaybe(PDFName.of('EmbeddedFiles'), PDFDict);
    if (!embeddedFiles) return null;

    const namesArray = embeddedFiles.lookupMaybe(PDFName.of('Names'), PDFArray);
    if (!namesArray) return null;

    // Names array alternates: [nameObj, fileSpecDict, nameObj, fileSpecDict, ...]
    for (let i = 0; i + 1 < namesArray.size(); i += 2) {
        const nameObj = namesArray.lookup(i);
        // PDFHexString / PDFString — get decoded text
        const nameStr = nameObj.decodeText ? nameObj.decodeText() : nameObj.asString();
        if (nameStr !== 'source.md') continue;

        const fileSpec = namesArray.lookup(i + 1, PDFDict);
        const efDict = fileSpec.lookupMaybe(PDFName.of('EF'), PDFDict);
        if (!efDict) return null;

        // lookupMaybe with a type class fails for PDFRawStream; use lookup without type constraint
        const fileStream = efDict.lookup(PDFName.of('F'));
        if (!fileStream) return null;

        // getContents() returns the raw (possibly compressed) stream bytes.
        // pdf-lib compresses attachments with FlateDecode by default.
        const rawBytes = fileStream.getContents();
        const buf = Buffer.from(rawBytes);

        // Detect FlateDecode compression by zlib magic header (0x78 0x??)
        if (buf.length >= 2 && buf[0] === 0x78) {
            return zlib.inflateSync(buf).toString('utf8');
        }
        return buf.toString('utf8');
    }

    return null;  // attachment not found
}

module.exports = { embedMarkdownInPdf, extractMarkdownFromPdf };

// CLI round-trip test
if (require.main === module) {
    const inputPdf = path.resolve(process.argv[2] || path.join(__dirname, '../out/output.pdf'));
    const inputMd  = path.resolve(process.argv[3] || path.join(__dirname, '../test/sample.md'));
    const outputMdPdf = path.resolve(process.argv[4] || path.join(__dirname, '../out/output.md.pdf'));

    (async () => {
        if (!fs.existsSync(inputPdf)) {
            console.error(`Input PDF not found: ${inputPdf}`);
            console.error('Run "node src/convert.js" first to generate the PDF.');
            process.exit(1);
        }

        const pdfBytes = fs.readFileSync(inputPdf);
        const markdown = fs.readFileSync(inputMd, 'utf8');

        console.log(`[embed] Embedding source.md into ${path.basename(inputPdf)}...`);
        const mdPdfBytes = await embedMarkdownInPdf(pdfBytes, markdown);
        fs.writeFileSync(outputMdPdf, mdPdfBytes);
        console.log(`✓ .md.pdf written to ${outputMdPdf}`);

        console.log(`[embed] Extracting source.md from ${path.basename(outputMdPdf)}...`);
        const extracted = await extractMarkdownFromPdf(mdPdfBytes);

        if (extracted === null) {
            console.error('✗ Extraction failed — attachment not found in PDF.');
            process.exit(1);
        }
        if (extracted !== markdown) {
            console.error('✗ Round-trip FAILED — extracted text does not match original.');
            console.error(`  Original length:  ${markdown.length}`);
            console.error(`  Extracted length: ${extracted.length}`);
            process.exit(1);
        }

        console.log('✓ Round-trip PASSED — extracted markdown matches original exactly.');
        console.log(`  Open ${outputMdPdf} in a PDF viewer to confirm pages are visible.`);
    })().catch(err => {
        console.error('Error:', err.message);
        process.exit(1);
    });
}
